url: https://vaclavkosar.com
name: Vaclav Kosar
title: Vaclav Kosar
author: Vaclav Kosar
description: a software & ML developer's blog on technology
keywords: blog, personal page, software development, software, technology, tips, cv, Vaclav Kosar, Kosar, Vaclav, Václav Košař,Václav Košař, Václav, portfolio

markdown: kramdown
twitter_username: vackosar
future: true
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-feed
  - jekyll-sitemap
plugins:
  - jekyll-feed
  - jekyll-sitemap
