url: https://vaclavkosar.com
name: Vaclav Kosar
title: Vaclav Kosar's Blog
author: Vaclav Kosar
description: Software, Machine Learning, & Business
tagline: a developer on tech
keywords: blog, personal page, software development, machine learning, software, technology, tips, cv, Vaclav Kosar, Kosar, Vaclav, Václav Košař,Václav Košař, Václav, portfolio

markdown: kramdown
twitter: vackosar
logo: /vaclav_face_circle.png
feedback_url: https://us3.list-manage.com/contact-form?u=289873d7958b1bdc1c6dc93b7&form_id=3b80462ee1d82c5a36e447efbfdbe72a

twitter_username: vackosar
future: true
show_downloads: true
theme: jekyll-theme-minimal
social:
  name: Vaclav Kosar
  links:
    - https://www.facebook.com/vackosar
    - https://twitter.com/vackosar
    - https://www.linkedin.com/in/vaclav-kosar-47755863
    - https://www.youtube.com/channel/UC410o-X5Q_5OGAb0i16oskQ
    - https://github.com/vackosar
    - https://vaclavkosar.com/feed.xml

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

include:
 - .well-known